---
- name: Set installer architecture for x86
  set_fact:
    papertrail_installer_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Set installer architecture for Debian arm
  set_fact:
    papertrail_installer_arch: "arm64"
  when: ansible_architecture == "aarch64" and ansible_os_family == "Debian"

- name: Set installer architecture for RedHat arm
  set_fact:
    papertrail_installer_arch: "aarch64"
  when: ansible_architecture == "aarch64" and ansible_os_family == "RedHat"

- name: Include os family variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"
